<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'RightPlace\Vendor\Firebase\JWT\SignatureInvalidException' => $strauss_src . '/firebase/php-jwt/src/SignatureInvalidException.php',
   'RightPlace\Vendor\Firebase\JWT\BeforeValidException' => $strauss_src . '/firebase/php-jwt/src/BeforeValidException.php',
   'RightPlace\Vendor\Firebase\JWT\Key' => $strauss_src . '/firebase/php-jwt/src/Key.php',
   'RightPlace\Vendor\Firebase\JWT\JWK' => $strauss_src . '/firebase/php-jwt/src/JWK.php',
   'RightPlace\Vendor\Firebase\JWT\ExpiredException' => $strauss_src . '/firebase/php-jwt/src/ExpiredException.php',
   'RightPlace\Vendor\Firebase\JWT\JWT' => $strauss_src . '/firebase/php-jwt/src/JWT.php',
);